version: "3.9"  # optional since v1.27.0
services:
  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    container_name: cli
    tty: true
    stdin_open: true
    ports:
    - "8080:8080"
    volumes:
      - .:/usr/src
